import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { ForceToThirdPipe } from './force-to-third.pipe';
import { AutogeneratedDirective } from './autogenerated.directive';
import { AppRoutingModule } from './app-routing.module';
import { RouterModule } from '@angular/router';
import { ForceWielderComponent } from './force-wielder/force-wielder.component';

@NgModule({
  declarations: [
    AppComponent,
    ForceWielderComponent,
    ForceToThirdPipe,
    AutogeneratedDirective
  ],
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule,
    RouterModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
