import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { ForceWeilderComponent } from './force-weilder/force-weilder.component';
import { ForceToThirdPipe } from './force-to-third.pipe';
import { AutogeneratedDirective } from './autogenerated.directive';
import { AppRoutingModule } from './app-routing.module';
import { RouterModule } from '@angular/router';

@NgModule({
  declarations: [
    AppComponent,
    ForceWeilderComponent,
    ForceToThirdPipe,
    AutogeneratedDirective
  ],
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule,
    RouterModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
